name: journal-gpem_si-gp_highlights-2023
channels:
  - conda-forge
dependencies:
  - bash=5.0.*
  - boost=1.76.*
  - ceres-solver=2.0.*
  - cmake=3.22.*
  - cxxopts=2.2.*
  - cudatoolkit=11.2.*
  - cudnn=8.1.*
  - doctest=2.4.*
  - eigen=3.4.*
  - fmt=7.1.*  
  - gcc=11.2.*
  - git=2.34.*
  - gsl=2.7
  - gxx=11.2.*
  - ipykernel=6.6.*
  - jemalloc=5.2.*
  - make=4.3
  - openlibm=0.8.*
  - pathos=0.3.*
  - pkgconfig=1.5.*
  - pip=22.3.*
  - pybind11=2.6.*
  - python=3.9.*
  - scikit-learn=1.2.*
  - scipy=1.11.*
  - taskflow=3.1.*
  - pip:
    - deap==1.4.*
    - ipykernel==6.22.*
    - Markdown==3.4.*
    - matplotlib==3.7.*
    - xlsxwriter==3.0.*